include:
  - proxy.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      db_HOST: db
      db_USER: ioi
      db_PASSWORD: 0990
      db_DATABASE: homework_2
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      db_ROOT_PASSWORD: 0990
      db_DATABASE: homework_2
      db_USER: ioi
      db_PASSWORD: 0990
    restart: always
    env_file:
      - .env
