FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt && \
    echo "Installed packages:" && \
    pip list

COPY . .

RUN which uvicorn || echo "uvicorn not found!"

CMD ["/usr/local/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]